language: rust
rust:
  - stable
cache: cargo
script:
  - nvm install stable
  - nvm use stable
  - yarn --cwd assets install
  - yarn --cwd assets run build
  - cargo build
  - bash update_protocols.sh
  - target/debug/wayland-protocol-docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./site
  on:
    branch: master
