language: rust
rust:
  - stable
node_js:
  - "lts/*"
cache: cargo
script:
  - ./build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./site
  on:
    branch: master
