language: rust
rust:
  - stable
cache:
  cargo: true
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - nvm install stable
  - nvm use stable

script:
  - yarn --cwd assets install
  - yarn --cwd assets run build
  - cargo build
  - bash update_protocols.sh
  - target/debug/wayland-protocol-docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./site
  on:
    branch: master
