#!/bin/bash

yarn --cwd assets run watch &
# live-server --port=8080 site > /dev/null &
yarn --cwd assets run serve &
cargo watch -x 'run' -w src -w templates -w wayland-protocol-docs-derive &
echo "Watching and reloading files.."
trap "jobs -p | xargs kill" SIGINT
wait
