[package]
name = "wayland-protocol-docs-derive"
version = "0.1.0"
authors = ["Ho-Yon Mak <hoyon.mak@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.23"
quote = "1.0.6"
proc-macro2 = "1.0.15"
